// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdAnalysis.Infrastructure.Persistence;

#nullable disable

namespace ProdAnalysis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118110532_AddDeviationEvents")]
    partial class AddDeviationEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.DeviationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualQty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentEscalationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviationQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HourIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HourStart")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HourlyRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanQty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionDayId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedByUserId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HourlyRecordId");

                    b.HasIndex("ProductionDayId");

                    b.HasIndex("ProductionDate", "WorkCenterId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("DeviationEvents", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.DowntimeReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DowntimeReasons", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.EscalationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviationEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviationEventId", "Level", "CreatedAt");

                    b.ToTable("EscalationLogs", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.HourlyDowntime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DowntimeReasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HourlyRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeReasonId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("HourlyRecordId", "DowntimeReasonId")
                        .IsUnique();

                    b.ToTable("HourlyDowntimes", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.HourlyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("HourIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HourStart")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanQty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductionDayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("ProductionDayId", "HourIndex")
                        .IsUnique();

                    b.ToTable("HourlyRecords", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.ProductionDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftEnd")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftStart")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaktSec")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkCenterId");

                    b.HasIndex("Date", "ShiftStart", "WorkCenterId")
                        .IsUnique();

                    b.ToTable("ProductionDays", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.WorkCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkCenters", (string)null);
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.DeviationEvent", b =>
                {
                    b.HasOne("ProdAnalysis.Domain.Entities.AppUser", "AcknowledgedByUser")
                        .WithMany()
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProdAnalysis.Domain.Entities.AppUser", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProdAnalysis.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProdAnalysis.Domain.Entities.HourlyRecord", "HourlyRecord")
                        .WithMany()
                        .HasForeignKey("HourlyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdAnalysis.Domain.Entities.ProductionDay", "ProductionDay")
                        .WithMany()
                        .HasForeignKey("ProductionDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcknowledgedByUser");

                    b.Navigation("ClosedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("HourlyRecord");

                    b.Navigation("ProductionDay");
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.EscalationLog", b =>
                {
                    b.HasOne("ProdAnalysis.Domain.Entities.DeviationEvent", "DeviationEvent")
                        .WithMany("EscalationLogs")
                        .HasForeignKey("DeviationEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviationEvent");
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.HourlyDowntime", b =>
                {
                    b.HasOne("ProdAnalysis.Domain.Entities.DowntimeReason", "DowntimeReason")
                        .WithMany()
                        .HasForeignKey("DowntimeReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProdAnalysis.Domain.Entities.HourlyRecord", "HourlyRecord")
                        .WithMany("HourlyDowntimes")
                        .HasForeignKey("HourlyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdAnalysis.Domain.Entities.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DowntimeReason");

                    b.Navigation("HourlyRecord");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.HourlyRecord", b =>
                {
                    b.HasOne("ProdAnalysis.Domain.Entities.ProductionDay", "ProductionDay")
                        .WithMany("HourlyRecords")
                        .HasForeignKey("ProductionDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdAnalysis.Domain.Entities.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductionDay");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.ProductionDay", b =>
                {
                    b.HasOne("ProdAnalysis.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProdAnalysis.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProdAnalysis.Domain.Entities.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.DeviationEvent", b =>
                {
                    b.Navigation("EscalationLogs");
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.HourlyRecord", b =>
                {
                    b.Navigation("HourlyDowntimes");
                });

            modelBuilder.Entity("ProdAnalysis.Domain.Entities.ProductionDay", b =>
                {
                    b.Navigation("HourlyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
